export enum TripStatus {
  OFFLINE = "OFFLINE",
  SEARCHING_DRIVER = "SEARCHING_DRIVER",
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  TRIP_STARTED = "TRIP_STARTED",
  TRIP_COMPLETED = "TRIP_COMPLETED",
  PENDING_PAYMENT = "PENDING_PAYMENT",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  CANCELLED_BY_DRIVER = "CANCELLED_BY_DRIVER",
  CANCELLED_BY_RIDER = "CANCELLED_BY_RIDER",
  NO_DRIVER_FOUND = "NO_DRIVER_FOUND",
}
