import { LocationName } from "../../constants/enum.locations";
import { ILocation } from "./location.interface";

export const locationsData: ILocation[] = [
  {
    name: LocationName.BANANI,
    description: "Commercial and residential area",
    fares: [
      { destination: LocationName.GULSHAN, fare: 150 },
      { destination: LocationName.MIRPUR, fare: 200 },
      { destination: LocationName.UTTARA, fare: 300 },
      { destination: LocationName.DHANMONDI, fare: 250 },
      { destination: LocationName.MOTIJHEEL, fare: 350 },
      { destination: LocationName.FARMGATE, fare: 200 },
      { destination: LocationName.MOHAKHALI, fare: 100 },
      { destination: LocationName.BASHUNDHARA, fare: 180 },
      { destination: LocationName.SHAHBAGH, fare: 280 },
    ],
  },
  {
    name: LocationName.GULSHAN,
    description: "Upscale diplomatic zone",
    fares: [
      { destination: LocationName.BANANI, fare: 150 },
      { destination: LocationName.MIRPUR, fare: 220 },
      { destination: LocationName.UTTARA, fare: 320 },
      { destination: LocationName.DHANMONDI, fare: 270 },
      { destination: LocationName.MOTIJHEEL, fare: 370 },
      { destination: LocationName.FARMGATE, fare: 210 },
      { destination: LocationName.MOHAKHALI, fare: 120 },
      { destination: LocationName.BASHUNDHARA, fare: 160 },
      { destination: LocationName.SHAHBAGH, fare: 290 },
    ],
  },
  {
    name: LocationName.MIRPUR,
    description: "Residential and stadium area",
    fares: [
      { destination: LocationName.BANANI, fare: 200 },
      { destination: LocationName.GULSHAN, fare: 220 },
      { destination: LocationName.UTTARA, fare: 180 },
      { destination: LocationName.DHANMONDI, fare: 240 },
      { destination: LocationName.MOTIJHEEL, fare: 360 },
      { destination: LocationName.FARMGATE, fare: 190 },
      { destination: LocationName.MOHAKHALI, fare: 170 },
      { destination: LocationName.BASHUNDHARA, fare: 260 },
      { destination: LocationName.SHAHBAGH, fare: 300 },
    ],
  },
  {
    name: LocationName.UTTARA,
    description: "Residential hub near airport",
    fares: [
      { destination: LocationName.BANANI, fare: 300 },
      { destination: LocationName.GULSHAN, fare: 320 },
      { destination: LocationName.MIRPUR, fare: 180 },
      { destination: LocationName.DHANMONDI, fare: 350 },
      { destination: LocationName.MOTIJHEEL, fare: 400 },
      { destination: LocationName.FARMGATE, fare: 280 },
      { destination: LocationName.MOHAKHALI, fare: 260 },
      { destination: LocationName.BASHUNDHARA, fare: 200 },
      { destination: LocationName.SHAHBAGH, fare: 370 },
    ],
  },
  {
    name: LocationName.DHANMONDI,
    description: "Educational and residential hub",
    fares: [
      { destination: LocationName.BANANI, fare: 250 },
      { destination: LocationName.GULSHAN, fare: 270 },
      { destination: LocationName.MIRPUR, fare: 240 },
      { destination: LocationName.UTTARA, fare: 350 },
      { destination: LocationName.MOTIJHEEL, fare: 200 },
      { destination: LocationName.FARMGATE, fare: 150 },
      { destination: LocationName.MOHAKHALI, fare: 230 },
      { destination: LocationName.BASHUNDHARA, fare: 300 },
      { destination: LocationName.SHAHBAGH, fare: 120 },
    ],
  },
  {
    name: LocationName.MOTIJHEEL,
    description: "Business district",
    fares: [
      { destination: LocationName.BANANI, fare: 350 },
      { destination: LocationName.GULSHAN, fare: 370 },
      { destination: LocationName.MIRPUR, fare: 360 },
      { destination: LocationName.UTTARA, fare: 400 },
      { destination: LocationName.DHANMONDI, fare: 200 },
      { destination: LocationName.FARMGATE, fare: 150 },
      { destination: LocationName.MOHAKHALI, fare: 280 },
      { destination: LocationName.BASHUNDHARA, fare: 320 },
      { destination: LocationName.SHAHBAGH, fare: 170 },
    ],
  },
  {
    name: LocationName.FARMGATE,
    description: "Busy commercial transport hub",
    fares: [
      { destination: LocationName.BANANI, fare: 200 },
      { destination: LocationName.GULSHAN, fare: 210 },
      { destination: LocationName.MIRPUR, fare: 190 },
      { destination: LocationName.UTTARA, fare: 280 },
      { destination: LocationName.DHANMONDI, fare: 150 },
      { destination: LocationName.MOTIJHEEL, fare: 150 },
      { destination: LocationName.MOHAKHALI, fare: 140 },
      { destination: LocationName.BASHUNDHARA, fare: 270 },
      { destination: LocationName.SHAHBAGH, fare: 160 },
    ],
  },
  {
    name: LocationName.MOHAKHALI,
    description: "Transport and commercial hub",
    fares: [
      { destination: LocationName.BANANI, fare: 100 },
      { destination: LocationName.GULSHAN, fare: 120 },
      { destination: LocationName.MIRPUR, fare: 170 },
      { destination: LocationName.UTTARA, fare: 260 },
      { destination: LocationName.DHANMONDI, fare: 230 },
      { destination: LocationName.MOTIJHEEL, fare: 280 },
      { destination: LocationName.FARMGATE, fare: 140 },
      { destination: LocationName.BASHUNDHARA, fare: 190 },
      { destination: LocationName.SHAHBAGH, fare: 250 },
    ],
  },
  {
    name: LocationName.BASHUNDHARA,
    description: "Residential and shopping hub",
    fares: [
      { destination: LocationName.BANANI, fare: 180 },
      { destination: LocationName.GULSHAN, fare: 160 },
      { destination: LocationName.MIRPUR, fare: 260 },
      { destination: LocationName.UTTARA, fare: 200 },
      { destination: LocationName.DHANMONDI, fare: 300 },
      { destination: LocationName.MOTIJHEEL, fare: 320 },
      { destination: LocationName.FARMGATE, fare: 270 },
      { destination: LocationName.MOHAKHALI, fare: 190 },
      { destination: LocationName.SHAHBAGH, fare: 310 },
    ],
  },
  {
    name: LocationName.SHAHBAGH,
    description: "Cultural and educational hub",
    fares: [
      { destination: LocationName.BANANI, fare: 280 },
      { destination: LocationName.GULSHAN, fare: 290 },
      { destination: LocationName.MIRPUR, fare: 300 },
      { destination: LocationName.UTTARA, fare: 370 },
      { destination: LocationName.DHANMONDI, fare: 120 },
      { destination: LocationName.MOTIJHEEL, fare: 170 },
      { destination: LocationName.FARMGATE, fare: 160 },
      { destination: LocationName.MOHAKHALI, fare: 250 },
      { destination: LocationName.BASHUNDHARA, fare: 310 },
    ],
  },
];
